blank_issues_enabled: false
contact_links:
  - name: DevLan Discord Community
    url: https://discord.io/devlan
    about: DevLan also has a Discord Community for you to make suggestions, discuss features or just chat around.
